modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MEGA SHOWDOWN LICENSE v2.1"

[[mods]]
modId = "mega_showdown"
version = "${version}"
displayName = "Cobblemon:Mega Showdown"
authors = "Yajat Kaul"
description = '''
Adding mega evolutions, z-moves, teralization, dynamax, ultra burst and fusions to the game
Features
- Cosmetics
- All form changes
- Ridding supported
- All 48 megas
- Accessories support
- Adds primal's
- Adds tera gimmik
- Adds mega gimmik
- Adds z moves gimmik
- Adds dynamax gimmik
- Adds ultra burst gimmik
- All fusion mons
'''
logoFile = "assets/mega_showdown/icon.png"

[[dependencies.mega_showdown]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.214,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mega_showdown]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mega_showdown]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mega_showdown]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.1, )"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mega_showdown]]
modId = "accessories"
type = "required"
versionRange = "[1.1.0-beta.52+1.21.1, )"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mega_showdown.mixins.json"

[[mixins]]
config = "mega_showdown.neoforge.mixins.json"
