modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "mega_showdown"
version = "${version}"
displayName = "Cobblemon: Mega Showdown"
authors = "YajatKaul"
description = '''
Adding all the megas to the game
'''
#logoFile = ""

[[dependencies.mega_showdown]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mega_showdown]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mega_showdown]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mega_showdown]]
modId = "curios"
mandatory = true
versionRange = "[9.2.2+1.21.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mixins.mega_showdown.json"